name: TownyPay
version: '${project.version}'
main: com.tanukicraft.townypay.TownyPay
api-version: '1.20'
load: POSTWORLD
depend: [Towny]

description: This is a plugin that create a daily pay for Mayors and Kings, and creates a daily budget for Towns and Nations to spend.