#TownyPay
#Made by Tomhmagic for TanukiCraft
#Check out our server running towny at play.tanukicraft.net
#https://discord.gg/zd7pvJY9Zr

#--------------------------------------------#
#            TownyPay Config                 #
#--------------------------------------------#

#Use these 2 settings if you don't want to pay Mayors and/or Kings
#Useful if you just want the budget system

#Enable Mayor Pay
EnableMayorPay: true
#Enable King Pay
EnableKingPay: true

#--------------------------------------------#
#              Town Settings                 #
#--------------------------------------------#

#Profit setting for towns, profit is worked out as
#(Current balance - (TownProfitCalc * upkeep))
TownProfitCalc: 2.0

#If true, MayorPay  and MayorPayTax would be a fixed amount, not percentage
MayorPayFixedAmount: false
#Percentage of profit paid to mayor
MayorPay: 30.0
#Percentage of tax to take from the pay, if MayorPayFixedAmount is true, this cannot be higher than MayorPay
MayorPayTax: 20.0
#Minimum balance before the system will pay a Mayor, if using MayorPayFixedAmount, set this no less than MayorPay
#if MayorPayFixedAmount is false, than it will use the profit to calculate Mayors pay
TownMinBal: 0.0

#If true, TownBudget would be a fixed amount, not percentage, tax is always a percentage
TownFixedBudget: false
#Percentage of profit
TownBudget: 10.0
#If TownFixedBudget false, set an amount for a minimum for the percentage calculations to return a budget.
#Must be higher than 0.0
TownMinProfit: 1.0
#How much tax to take from paying a resident in the same town
TownPayTax: 10.0
#How much tax to take from paying a resident not in the same town
TownPayOutsiderTax: 20.0


#--------------------------------------------#
#             Nation Settings                #
#--------------------------------------------#

#Profit setting for nations, profit is worked out as
#(Current balance - (NationProfitCalc * upkeep))
NationProfitCalc: 2.0

#If true, KingPay and KingPayTax would be a fixed amount, not percentage
KingPayFixedAmount: false
#Percentage of profit paid to king
KingPay: 30.0
#Percentage of tax to take from the pay, if KingPayFixedAmount is true, this cannot be higher than KingPay
KingPayTax: 20.0
#Minimum balance before the system will pay a King, if using KingPayFixedAmount, set this no less than KingPay
#if KingPayFixedAmount is false, than it will use the profit to calculate Kings pay
NationMinBal: 0.0

#If true, NationBudget would be a fixed amount, not percentage tax is always a percentage
#Profit is (Current balance - 2*upkeep)
NationFixedBudget: false
#Percentage of profit
NationBudget: 10.0
#If NationFixedBudget false, set an amount for a minimum for the profit calculations to return a budget.
#Must be higher than 0.0
NationMinProfit: 1.0
#How much tax to take from paying a resident in the same nation
NationPayTax: 10.0
#How much tax to take from paying a resident not in the same nation
NationPayOutsiderTax: 20.0


